version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: "${BACKEND_NAME}"
    restart: always
    env_file: .env
    volumes:
      - type: bind
        source: ./backend/src
        target: /usr/src/app/src
    expose: 
      - "${API_PORT}"
    ports: 
      - "${API_PORT}:${API_PORT}"
    command: npm run watch
    environment: 
      - PORT=${API_PORT}
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

  db:
    image: postgres
    restart: always
    env_file: .env
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}